# Generated by Django 5.0.1 on 2025-03-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='end',
            new_name='end_date',
        ),
    ]
